/* jshint esnext: true */
import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);
import '@/common/stylus/index.styl';

export default new Router({
  // mode: 'history',
  linkActiveClass: 'active',
  routes: [
    {path: '*', redirect: '/home'},
    {path: '/home', component: resolve => require(['@/components/home/home'], resolve), name: 'home'},
    {path: '/category', component: resolve => require(['@/components/category/category'], resolve)},
    {path: '/search', component: resolve => require(['@/components/search/search'], resolve), name: 'search'},
    {path: '/good/:id', component: resolve => require(['@/components/good-detail/good-detailv2'], resolve), name: 'good'},
    {path: '/good/:id/comments', component: resolve => require(['@/components/good-detail/comments'], resolve), name: 'goodComment'},
    {path: '/cart', component: resolve => require(['@/components/cart/shopcart'], resolve)},
    {path: '/pay', component: resolve => require(['@/components/cart/pay'], resolve), name: 'pay'},
    {path: '/pay/deposit', component: resolve => require(['@/components/cart/deposit'], resolve), name: 'deposit'},
    {path: '/pay/remark', component: resolve => require(['@/components/cart/remark'], resolve)},
    {path: '/address', component: resolve => require(['@/components/my/addressList'], resolve), name: 'addresslist'},
    {path: '/address/add', component: resolve => require(['@/components/my/addAddress'], resolve), name: 'addaddress'},
    {path: '/address/:id/edit', component: resolve => require(['@/components/my/editAddress'], resolve), name: 'address'},
    {path: '/order', component: resolve => require(['@/components/order/order'], resolve), name: 'order'},
    {path: '/order/:id', component: resolve => require(['@/components/order/orderdetail'], resolve), name: 'orderdetail'},
    {path: '/order/refund/:id', component: resolve => require(['@/components/order/refund'], resolve), name: 'refund'},
    {path: '/order/express/:expressCode/:expressNo', component: resolve => require(['@/components/order/expresslog'], resolve), name: 'expresslog'},
    {path: '/order/:id/address', component: resolve => require(['@/components/my/fillAddress'], resolve), name: 'filladdress'},
    {path: '/auction', component: resolve => require(['@/components/auction/auctions'], resolve), name: 'auction'},
    {path: '/auction/:id/detail', component: resolve => require(['@/components/auction/auctiondetail'], resolve), name: 'auctiondetail'},
    {path: '/auction/list/:id', component: resolve => require(['@/components/auction/auctionList'], resolve), name: 'auctionList'},
    {path: '/auction/:id/bidlist', component: resolve => require(['@/components/auction/bidlist'], resolve), name: 'bidlist'},
    {path: '/myauction', component: resolve => require(['@/components/auction/myauction'], resolve), name: 'myauction'},
    {path: '/coupon', component: resolve => require(['@/components/coupon/coupon'], resolve), name: 'coupon'},
    {path: '/getcoupon', component: resolve => require(['@/components/coupon/getcoupon2'], resolve), name: 'getcoupon'},
    {path: '/coupon/history', component: resolve => require(['@/components/coupon/coupon-history'], resolve), name: 'couponHistory'},
    {path: '/coupon/new', component: resolve => require(['@/components/coupon/newcoupon'], resolve), name: 'newcoupon'},
    {path: '/discount/ticket', component: resolve => require(['@/components/coupon/usecoupon'], resolve), name: 'usecoupon'},
    {path: '/footprint', component: resolve => require(['@/components/footprint/footprint'], resolve), name: 'footprint'},
    {path: '/follow', component: resolve => require(['@/components/follow/follow'], resolve), name: 'follow'},
    {path: '/seckill', component: resolve => require(['@/components/seckill/seckill'], resolve), name: 'seckill'},
    {path: '/seckill/:id/detail', component: resolve => require(['@/components/seckill/seckilldetail'], resolve), name: 'seckillDetail'},
    {path: '/myseckill', component: resolve => require(['@/components/seckill/myseckill'], resolve), name: 'myseckill'},
    {path: '/groupbuy', component: resolve => require(['@/components/groupbuy/groupbuy'], resolve), name: 'groupbuy'},
    {path: '/groupbuy/:id/detail', component: resolve => require(['@/components/groupbuy/groupbuydetail'], resolve), name: 'groupbuyDetail'},
    {path: '/mygroupbuy', component: resolve => require(['@/components/groupbuy/mygroupbuy'], resolve), name: 'mygroupbuy'},
    {path: '/personInfo', component: resolve => require(['@/components/my/personInfo'], resolve)},
    {path: '/wallet', component: resolve => require(['@/components/my/wallet'], resolve)},
    {path: '/cashdetail', component: resolve => require(['@/components/my/cashdetail'], resolve)},
    {path: '/myrecommend', component: resolve => require(['@/components/my/myrecommend'], resolve), name: 'myrecommend'},
    {path: '/recommend/:id', component: resolve => require(['@/components/my/recommend'], resolve), name: 'recommend'},
    // {path: '/address/citychoose', component: citychoose, name: 'citychoose'},
    {path: '/cashback', component: resolve => require(['@/components/my/cashback'], resolve)},
    {path: '/cashbackdetail', component: resolve => require(['@/components/my/cashbackdetail'], resolve)},
    {path: '/bindphone', component: resolve => require(['@/components/my/bindphone'], resolve), name: 'bindphone'},
    {path: '/articles', component: resolve => require(['@/components/article/articles'], resolve), name: 'articles'},
    {path: '/article/:id', component: resolve => require(['@/components/article/articledetail'], resolve), name: 'articledetail'},
    {path: '/stat', component: resolve => require(['@/components/stats/stat'], resolve), name: 'stat'},
    {path: '/uvdetail', component: resolve => require(['@/components/stats/uv_detail'], resolve), name: 'uvdetail'},
    {path: '/wip_bargain', component: resolve => require(['@/components/stats/wip_bargains'], resolve), name: 'wipbargain'},
    {path: '/wip_tuan', component: resolve => require(['@/components/stats/wip_tuans'], resolve), name: 'wiptuan'},
    {path: '/firstpurchase', component: resolve => require(['@/components/firstpurchase/firstpurchase'], resolve), name: 'firstpurchase'},
    {path: '/firstpurchase/:id', component: resolve => require(['@/components/firstpurchase/firstdetail'], resolve), name: 'firstdetail'},
    {path: '/sharepay', component: resolve => require(['@/components/sharepay/sharelist'], resolve), name: 'sharepay'},
    {path: '/sharepay/uvlog', component: resolve => require(['@/components/sharepay/visitlist'], resolve), name: 'visitlist'},
    {path: '/myshare', component: resolve => require(['@/components/sharepay/myshare'], resolve), name: 'myshare'},
    {path: '/sharepay/:id', component: resolve => require(['@/components/sharepay/sharedetail'], resolve), name: 'sharedetail'},
    {path: '/tuan', component: resolve => require(['@/components/tuan/tuanlist'], resolve), name: 'tuan'},
    {path: '/mytuan', component: resolve => require(['@/components/tuan/mytuan'], resolve), name: 'mytuan'},
    {path: '/tuan/:id', component: resolve => require(['@/components/tuan/tuandetail'], resolve), name: 'tuandetail'},
    {path: '/sharetuan/:id', component: resolve => require(['@/components/tuan/sharetuan'], resolve), name: 'sharetuan'},
    {path: '/signature', component: resolve => require(['@/components/common/signature'], resolve), name: 'signature'},
    {path: '/404', component: resolve => require(['@/components/common/404'], resolve), name: 'notfound'},
    {path: '/info', component: resolve => require(['@/components/common/info'], resolve), name: 'info'},
    {path: '/friends', component: resolve => require(['@/components/user/your_friends'], resolve), name: 'yourfriends'},
    {path: '/buyers', component: resolve => require(['@/components/user/your_buyers'], resolve), name: 'yourbuyers'},
    {path: '/buyers/:uid', component: resolve => require(['@/components/user/your_orders'], resolve), name: 'yourorders'},
    {path: '/task', component: resolve => require(['@/components/common/task'], resolve), name: 'task'},
    {path: '/my', component: resolve => require(['@/components/my/my'], resolve)}
  ]
});
